name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Print working directory
      run: pwd

    - name: List root directory contents
      run: ls -la

    - name: List all contents recursively
      run: find .

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Set Node.js options to bypass OpenSSL issue
      run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

    - name: Locate package.json
      run: find . -name package.json

    - name: Locate package-lock.json
      run: find . -name package-lock.json

    - name: Install dependencies
      run: |
        if [ -f "./package-lock.json" ]; then
          npm ci
        elif [ -f "./react-frontend/package-lock.json" ]; then
          cd react-frontend && npm ci
        else
          echo "Cannot find package-lock.json"
          exit 1
        fi

    - name: Build
      run: |
        if [ -f "./package.json" ]; then
          npm run build --if-present
        elif [ -f "./react-frontend/package.json" ]; then
          cd react-frontend && npm run build --if-present
        else
          echo "Cannot find package.json"
          exit 1
        fi

    - name: Test
      run: |
        if [ -f "./package.json" ]; then
          npm test
        elif [ -f "./react-frontend/package.json" ]; then
          cd react-frontend && npm test
        else
          echo "Cannot find package.json"
          exit 1
        fi
